// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brpc/get_js.proto

#include "brpc/get_js.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace brpc {
PROTOBUF_CONSTEXPR GetJsRequest::GetJsRequest(
    ::_pbi::ConstantInitialized) {}
struct GetJsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetJsRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetJsRequestDefaultTypeInternal() {}
  union {
    GetJsRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetJsRequestDefaultTypeInternal _GetJsRequest_default_instance_;
PROTOBUF_CONSTEXPR GetJsResponse::GetJsResponse(
    ::_pbi::ConstantInitialized) {}
struct GetJsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetJsResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetJsResponseDefaultTypeInternal() {}
  union {
    GetJsResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetJsResponseDefaultTypeInternal _GetJsResponse_default_instance_;
}  // namespace brpc
static ::_pb::Metadata file_level_metadata_brpc_2fget_5fjs_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_brpc_2fget_5fjs_2eproto = nullptr;
static const ::_pb::ServiceDescriptor* file_level_service_descriptors_brpc_2fget_5fjs_2eproto[1];

const uint32_t TableStruct_brpc_2fget_5fjs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::brpc::GetJsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::brpc::GetJsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::brpc::GetJsRequest)},
  { 6, -1, -1, sizeof(::brpc::GetJsResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::brpc::_GetJsRequest_default_instance_._instance,
  &::brpc::_GetJsResponse_default_instance_._instance,
};

const char descriptor_table_protodef_brpc_2fget_5fjs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021brpc/get_js.proto\022\004brpc\"\016\n\014GetJsReques"
  "t\"\017\n\rGetJsResponse2\332\001\n\002js\0224\n\tsorttable\022\022"
  ".brpc.GetJsRequest\032\023.brpc.GetJsResponse\022"
  "5\n\njquery_min\022\022.brpc.GetJsRequest\032\023.brpc"
  ".GetJsResponse\0223\n\010flot_min\022\022.brpc.GetJsR"
  "equest\032\023.brpc.GetJsResponse\0222\n\007viz_min\022\022"
  ".brpc.GetJsRequest\032\023.brpc.GetJsResponseB"
  "\003\200\001\001"
  ;
static ::_pbi::once_flag descriptor_table_brpc_2fget_5fjs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_brpc_2fget_5fjs_2eproto = {
    false, false, 284, descriptor_table_protodef_brpc_2fget_5fjs_2eproto,
    "brpc/get_js.proto",
    &descriptor_table_brpc_2fget_5fjs_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_brpc_2fget_5fjs_2eproto::offsets,
    file_level_metadata_brpc_2fget_5fjs_2eproto, file_level_enum_descriptors_brpc_2fget_5fjs_2eproto,
    file_level_service_descriptors_brpc_2fget_5fjs_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_brpc_2fget_5fjs_2eproto_getter() {
  return &descriptor_table_brpc_2fget_5fjs_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_brpc_2fget_5fjs_2eproto(&descriptor_table_brpc_2fget_5fjs_2eproto);
namespace brpc {

// ===================================================================

class GetJsRequest::_Internal {
 public:
};

GetJsRequest::GetJsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:brpc.GetJsRequest)
}
GetJsRequest::GetJsRequest(const GetJsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:brpc.GetJsRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetJsRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetJsRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata GetJsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_brpc_2fget_5fjs_2eproto_getter, &descriptor_table_brpc_2fget_5fjs_2eproto_once,
      file_level_metadata_brpc_2fget_5fjs_2eproto[0]);
}

// ===================================================================

class GetJsResponse::_Internal {
 public:
};

GetJsResponse::GetJsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:brpc.GetJsResponse)
}
GetJsResponse::GetJsResponse(const GetJsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:brpc.GetJsResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetJsResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetJsResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata GetJsResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_brpc_2fget_5fjs_2eproto_getter, &descriptor_table_brpc_2fget_5fjs_2eproto_once,
      file_level_metadata_brpc_2fget_5fjs_2eproto[1]);
}

// ===================================================================

js::~js() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* js::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_brpc_2fget_5fjs_2eproto);
  return file_level_service_descriptors_brpc_2fget_5fjs_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* js::GetDescriptor() {
  return descriptor();
}

void js::sorttable(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::brpc::GetJsRequest*,
                         ::brpc::GetJsResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method sorttable() not implemented.");
  done->Run();
}

void js::jquery_min(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::brpc::GetJsRequest*,
                         ::brpc::GetJsResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method jquery_min() not implemented.");
  done->Run();
}

void js::flot_min(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::brpc::GetJsRequest*,
                         ::brpc::GetJsResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method flot_min() not implemented.");
  done->Run();
}

void js::viz_min(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::brpc::GetJsRequest*,
                         ::brpc::GetJsResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method viz_min() not implemented.");
  done->Run();
}

void js::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_brpc_2fget_5fjs_2eproto[0]);
  switch(method->index()) {
    case 0:
      sorttable(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::brpc::GetJsRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::brpc::GetJsResponse*>(
                 response),
             done);
      break;
    case 1:
      jquery_min(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::brpc::GetJsRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::brpc::GetJsResponse*>(
                 response),
             done);
      break;
    case 2:
      flot_min(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::brpc::GetJsRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::brpc::GetJsResponse*>(
                 response),
             done);
      break;
    case 3:
      viz_min(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::brpc::GetJsRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::brpc::GetJsResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& js::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::brpc::GetJsRequest::default_instance();
    case 1:
      return ::brpc::GetJsRequest::default_instance();
    case 2:
      return ::brpc::GetJsRequest::default_instance();
    case 3:
      return ::brpc::GetJsRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& js::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::brpc::GetJsResponse::default_instance();
    case 1:
      return ::brpc::GetJsResponse::default_instance();
    case 2:
      return ::brpc::GetJsResponse::default_instance();
    case 3:
      return ::brpc::GetJsResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

js_Stub::js_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
js_Stub::js_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
js_Stub::~js_Stub() {
  if (owns_channel_) delete channel_;
}

void js_Stub::sorttable(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::brpc::GetJsRequest* request,
                              ::brpc::GetJsResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void js_Stub::jquery_min(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::brpc::GetJsRequest* request,
                              ::brpc::GetJsResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void js_Stub::flot_min(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::brpc::GetJsRequest* request,
                              ::brpc::GetJsResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}
void js_Stub::viz_min(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::brpc::GetJsRequest* request,
                              ::brpc::GetJsResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(3),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace brpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::brpc::GetJsRequest*
Arena::CreateMaybeMessage< ::brpc::GetJsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::brpc::GetJsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::brpc::GetJsResponse*
Arena::CreateMaybeMessage< ::brpc::GetJsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::brpc::GetJsResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
